/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FreeRouteImport } from './routes/free'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FreeIndexRouteImport } from './routes/free/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as FreeAfkRouteImport } from './routes/free/afk'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPaidplansRouteImport } from './routes/admin/paidplans'
import { Route as AdminLinksRouteImport } from './routes/admin/links'
import { Route as AdminFreeplansRouteImport } from './routes/admin/freeplans'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeRoute = FreeRouteImport.update({
  id: '/free',
  path: '/free',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeIndexRoute = FreeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FreeRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FreeAfkRoute = FreeAfkRouteImport.update({
  id: '/afk',
  path: '/afk',
  getParentRoute: () => FreeRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaidplansRoute = AdminPaidplansRouteImport.update({
  id: '/paidplans',
  path: '/paidplans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFreeplansRoute = AdminFreeplansRouteImport.update({
  id: '/freeplans',
  path: '/freeplans',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/free': typeof FreeRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/freeplans': typeof AdminFreeplansRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/paidplans': typeof AdminPaidplansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/free/afk': typeof FreeAfkRoute
  '/admin/': typeof AdminIndexRoute
  '/free/': typeof FreeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/freeplans': typeof AdminFreeplansRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/paidplans': typeof AdminPaidplansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/free/afk': typeof FreeAfkRoute
  '/admin': typeof AdminIndexRoute
  '/free': typeof FreeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/free': typeof FreeRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/freeplans': typeof AdminFreeplansRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/paidplans': typeof AdminPaidplansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/free/afk': typeof FreeAfkRoute
  '/admin/': typeof AdminIndexRoute
  '/free/': typeof FreeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/free'
    | '/login'
    | '/signup'
    | '/admin/freeplans'
    | '/admin/links'
    | '/admin/paidplans'
    | '/admin/settings'
    | '/admin/users'
    | '/free/afk'
    | '/admin/'
    | '/free/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/freeplans'
    | '/admin/links'
    | '/admin/paidplans'
    | '/admin/settings'
    | '/admin/users'
    | '/free/afk'
    | '/admin'
    | '/free'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/free'
    | '/login'
    | '/signup'
    | '/admin/freeplans'
    | '/admin/links'
    | '/admin/paidplans'
    | '/admin/settings'
    | '/admin/users'
    | '/free/afk'
    | '/admin/'
    | '/free/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FreeRoute: typeof FreeRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free': {
      id: '/free'
      path: '/free'
      fullPath: '/free'
      preLoaderRoute: typeof FreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free/': {
      id: '/free/'
      path: '/'
      fullPath: '/free/'
      preLoaderRoute: typeof FreeIndexRouteImport
      parentRoute: typeof FreeRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/free/afk': {
      id: '/free/afk'
      path: '/afk'
      fullPath: '/free/afk'
      preLoaderRoute: typeof FreeAfkRouteImport
      parentRoute: typeof FreeRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paidplans': {
      id: '/admin/paidplans'
      path: '/paidplans'
      fullPath: '/admin/paidplans'
      preLoaderRoute: typeof AdminPaidplansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/freeplans': {
      id: '/admin/freeplans'
      path: '/freeplans'
      fullPath: '/admin/freeplans'
      preLoaderRoute: typeof AdminFreeplansRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFreeplansRoute: typeof AdminFreeplansRoute
  AdminLinksRoute: typeof AdminLinksRoute
  AdminPaidplansRoute: typeof AdminPaidplansRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFreeplansRoute: AdminFreeplansRoute,
  AdminLinksRoute: AdminLinksRoute,
  AdminPaidplansRoute: AdminPaidplansRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FreeRouteChildren {
  FreeAfkRoute: typeof FreeAfkRoute
  FreeIndexRoute: typeof FreeIndexRoute
}

const FreeRouteChildren: FreeRouteChildren = {
  FreeAfkRoute: FreeAfkRoute,
  FreeIndexRoute: FreeIndexRoute,
}

const FreeRouteWithChildren = FreeRoute._addFileChildren(FreeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FreeRoute: FreeRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
